#!/bin/sh
if test "z$*" = zversion ||
   test "z$*" = z--version
then
	echo 'git-gui version 0.20.0.44.gccc98'
else
	libdir="${GIT_GUI_LIB_DIR:-/usr/local/Cellar/git/2.13.0/share/git-gui/lib}"
	exec "$libdir/Git Gui.app/Contents/MacOS/Wish" "$0" "$@"
fi
